FROM node:22-alpine

WORKDIR /app

# Копируем все package файлы
COPY package*.json ./
COPY package-lock.json ./

# Установка ВСЕХ зависимостей (включая devDependencies)
RUN npm ci --include=dev

# Альтернативный вариант, если нужны только production зависимости:
# RUN npm ci --only=production

COPY . .

EXPOSE 3000

CMD ["sh", "-c", "echo 'Starting Vite...' && npm run dev -- --host 0.0.0.0"]