FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
COPY package-lock.json ./

RUN npm ci --include=dev

COPY . .

EXPOSE 3000

CMD ["sh", "-c", "echo 'Starting Vite...' && npm run dev -- --host 0.0.0.0"]