FROM python:3.11-slim

WORKDIR /app

# Установка Tesseract и системных зависимостей
# Заменили libgl1-mesa-glx на libgl1 для Debian Trixie
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    gcc \
    g++ \
    make \
    postgresql-client \
    tesseract-ocr \
    tesseract-ocr-eng \
    tesseract-ocr-rus \
    libtesseract-dev \
    libgl1 \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    libgomp1 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Копируем requirements
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код
COPY . .

# Создаем папки
RUN mkdir -p staticfiles && chmod 755 staticfiles
RUN mkdir -p freedraw_widget_backend/migrations && \
    touch freedraw_widget_backend/migrations/__init__.py

EXPOSE 8000

CMD ["daphne", "-b", "0.0.0.0", "-p", "8000", "freedraw_widget_backend.asgi:application"]
