import type { LatexSymbol } from '../types.ts';

export const latexSymbols: LatexSymbol[] = [
  { name: 'fraction', latex: '\\frac{a}{b}', description: 'Дробь с числителем и знаменателем', category: 'fraction', placeholder: '\\frac{a}{b}' },
  { name: 'sqrt', latex: '\\sqrt{x}', description: 'Квадратный корень', category: 'root', placeholder: '\\sqrt{x}' },
  { name: 'nthroot', latex: '\\sqrt[n]{x}', description: 'Корень с показателем степени', category: 'root', placeholder: '\\sqrt[n]{x}' },
  { name: 'superscript', latex: 'x^{2}', description: 'Надстрочный индекс', category: 'superscript', placeholder: 'x^{2}' },
  { name: 'subscript', latex: 'x_{i}', description: 'Подстрочный индекс', category: 'subscript', placeholder: 'x_{i}' },
  { name: 'sum', latex: '\\sum_{i=1}^{n}', description: 'Сумма', category: 'operators', placeholder: '\\sum_{i=1}^{n}' },
  { name: 'integral', latex: '\\int_{a}^{b}', description: 'Интеграл', category: 'operators', placeholder: '\\int_{a}^{b}' },
  { name: 'limit', latex: '\\lim_{x \\to 0}', description: 'Предел', category: 'operators', placeholder: '\\lim_{x \\to 0}' },
  { name: 'derivative', latex: '\\frac{dy}{dx}', description: 'Производная', category: 'operators', placeholder: '\\frac{dy}{dx}' },
  { name: 'infinity', latex: '\\infty', description: 'Символ бесконечности', category: 'symbols' },
  { name: 'approx', latex: '\\approx', description: 'Приблизительное равенство', category: 'symbols' },
  { name: 'neq', latex: '\\neq', description: 'Не равно', category: 'symbols' },
  { name: 'leq', latex: '\\leq', description: 'Меньше или равно', category: 'symbols' },
  { name: 'geq', latex: '\\geq', description: 'Больше или равно', category: 'symbols' },
  { name: 'in', latex: '\\in', description: 'Принадлежность множеству', category: 'symbols' },
  { name: 'forall', latex: '\\forall', description: 'Для всех', category: 'symbols' },
  { name: 'exists', latex: '\\exists', description: 'Существует', category: 'symbols' },
  { name: 'therefore', latex: '\\therefore', description: 'Следовательно', category: 'symbols' },
  { name: 'plus', latex: '+', description: 'Плюс', category: 'symbols' },
  { name: 'minus', latex: '-', description: 'Минус', category: 'symbols' },
  { name: 'times', latex: '\\times', description: 'Умножение', category: 'symbols' },
  { name: 'div', latex: '\\div', description: 'Деление', category: 'symbols' },
  { name: 'equals', latex: '=', description: 'Равно', category: 'symbols' },
  { name: 'parentheses', latex: '\\left( x \\right)', description: 'Круглые скобки', category: 'brackets', placeholder: '\\left( x + y \\right)' },
  { name: 'brackets', latex: '\\left[ a \\right]', description: 'Квадратные скобки', category: 'brackets', placeholder: '\\left[ a, b \\right]' },
  { name: 'braces', latex: '\\left\\{ x \\right\\}', description: 'Фигурные скобки', category: 'brackets', placeholder: '\\left\\{ x, y \\right\\}' },
  { name: 'abs', latex: '\\left| x \\right|', description: 'Модуль', category: 'brackets', placeholder: '\\left| x \\right|' },
  { name: 'alpha', latex: '\\alpha', description: 'Греческая буква альфа', category: 'symbols' },
  { name: 'beta', latex: '\\beta', description: 'Греческая буква бета', category: 'symbols' },
  { name: 'gamma', latex: '\\gamma', description: 'Греческая буква гамма', category: 'symbols' },
  { name: 'delta', latex: '\\delta', description: 'Греческая буква дельта', category: 'symbols' },
  { name: 'pi', latex: '\\pi', description: 'Число Пи', category: 'symbols' },
  { name: 'sigma', latex: '\\sigma', description: 'Греческая буква сигма', category: 'symbols' },
  { name: 'theta', latex: '\\theta', description: 'Греческая буква тета', category: 'symbols' },
];
