import type { LatexSymbol } from '../types.ts';

export const latexSymbols: LatexSymbol[] = [
  { name: 'Простая дробь', latex: '\\frac{}{}', description: 'Дробь с числителем и знаменателем', category: 'fraction', placeholder: '\\frac{a}{b}' },
  { name: 'Квадратный корень', latex: '\\sqrt{}', description: 'Квадратный корень', category: 'root', placeholder: '\\sqrt{x}' },
  { name: 'Корень n-ой степени', latex: '\\sqrt[]{}', description: 'Корень с показателем степени', category: 'root', placeholder: '\\sqrt[n]{x}' },
  { name: 'Верхний индекс', latex: '^{}', description: 'Надстрочный индекс', category: 'superscript', placeholder: 'x^{2}' },
  { name: 'Нижний индекс', latex: '_{}', description: 'Подстрочный индекс', category: 'subscript', placeholder: 'x_{i}' },
  { name: 'Сумма', latex: '\\sum_{}^{}', description: 'Сумма', category: 'operators', placeholder: '\\sum_{i=1}^{n}' },
  { name: 'Интеграл', latex: '\\int_{}^{}', description: 'Интеграл', category: 'operators', placeholder: '\\int_{a}^{b}' },
  { name: 'Предел', latex: '\\lim_{}', description: 'Предел', category: 'operators', placeholder: '\\lim_{x \\to 0}' },
  { name: 'Производная', latex: '\\frac{d}{dx}', description: 'Производная', category: 'operators', placeholder: '\\frac{dy}{dx}' },
  { name: 'Бесконечность', latex: '\\infty', description: 'Символ бесконечности', category: 'symbols' },
  { name: 'Приблизительно', latex: '\\approx', description: 'Приблизительное равенство', category: 'symbols' },
  { name: 'Не равно', latex: '\\neq', description: 'Не равно', category: 'symbols' },
  { name: 'Меньше или равно', latex: '\\leq', description: 'Меньше или равно', category: 'symbols' },
  { name: 'Больше или равно', latex: '\\geq', description: 'Больше или равно', category: 'symbols' },
  { name: 'Принадлежит', latex: '\\in', description: 'Принадлежность множеству', category: 'symbols' },
  { name: 'Для всех', latex: '\\forall', description: 'Для всех', category: 'symbols' },
  { name: 'Существует', latex: '\\exists', description: 'Существует', category: 'symbols' },
  { name: 'Следовательно', latex: '\\therefore', description: 'Следовательно', category: 'symbols' },
  { name: 'Плюс', latex: '+', description: 'Плюс', category: 'symbols' },
  { name: 'Минус', latex: '-', description: 'Минус', category: 'symbols' },
  { name: 'Умножить', latex: '\\times', description: 'Умножение', category: 'symbols' },
  { name: 'Делить', latex: '\\div', description: 'Деление', category: 'symbols' },
  { name: 'Равно', latex: '=', description: 'Равно', category: 'symbols' },
  { name: 'Круглые скобки', latex: '\\left( \\right)', description: 'Круглые скобки', category: 'brackets', placeholder: '\\left( x + y \\right)' },
  { name: 'Квадратные скобки', latex: '\\left[ \\right]', description: 'Квадратные скобки', category: 'brackets', placeholder: '\\left[ a, b \\right]' },
  { name: 'Фигурные скобки', latex: '\\left\\{ \\right\\}', description: 'Фигурные скобки', category: 'brackets', placeholder: '\\left\\{ x, y \\right\\}' },
  { name: 'Модуль', latex: '\\left| \\right|', description: 'Модуль', category: 'brackets', placeholder: '\\left| x \\right|' },
  { name: 'Альфа', latex: '\\alpha', description: 'Греческая буква альфа', category: 'symbols' },
  { name: 'Бета', latex: '\\beta', description: 'Греческая буква бета', category: 'symbols' },
  { name: 'Гамма', latex: '\\gamma', description: 'Греческая буква гамма', category: 'symbols' },
  { name: 'Дельта', latex: '\\delta', description: 'Греческая буква дельта', category: 'symbols' },
  { name: 'Пи', latex: '\\pi', description: 'Число Пи', category: 'symbols' },
  { name: 'Сигма', latex: '\\sigma', description: 'Греческая буква сигма', category: 'symbols' },
  { name: 'Тета', latex: '\\theta', description: 'Греческая буква тета', category: 'symbols' },
];