# Generated by Django 4.2.24 on 2025-12-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.CharField(help_text='ID доски из внешней системы', max_length=255, unique=True, verbose_name='ID доски')),
                ('elements', models.JSONField(blank=True, default=list, help_text='JSON массив с элементами рисования', verbose_name='Элементы холста')),
                ('canvas_config', models.JSONField(blank=True, default=dict, help_text='JSON конфигурация холста', verbose_name='Конфигурация холста')),
                ('history', models.JSONField(blank=True, default=list, help_text='JSON с историей изменений для undo/redo', verbose_name='История изменений')),
                ('active_users', models.JSONField(blank=True, default=list, help_text='Список активных пользователей', verbose_name='Активные пользователи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Данные холста',
                'verbose_name_plural': 'Данные холстов',
                'indexes': [models.Index(fields=['board_id'], name='freedraw_wi_board_i_cd524b_idx')],
            },
        ),
    ]
